export type Technologies =
  | 'C'
  | 'C++'
  | 'Java'
  | 'C#'
  | 'JS'
  | 'HTML'
  | 'Python'
  | 'Bash'
  | 'SLANG'
  | 'TailwindCSS'
  | 'CSS Modules'
  | 'Styled Components'
  | 'SASS'
  | 'LESS'
  | 'PostCSS'
  | 'CSS in JS'
  | 'Sass Modules'
  | 'React'
  | 'ReactJS'
  | 'Angular'
  | 'Vue'
  | 'Svelte'
  | 'Ember'
  | 'Backbone'
  | 'jQuery'
  | 'Vanilla JS'
  | 'TS'
  | 'TypeScript'
  | 'Redux'
  | 'Service Workers'
  | 'NextJS'
  | 'Vite'
  | 'Gatsby'
  | 'CRA'
  | 'Django'
  | 'Unity'
  | 'Android'
  | 'Spring Boot'
  | 'Flask'
  | 'FastAPI'
  | 'Spring'
  | 'Hibernate'
  | 'Liquibase'
  | 'Project Reactor'
  | 'Vertx'
  | 'mailgun.js'
  | 'imgui'
  | 'glfw'
  | 'allauth'
  | 'OpenCV'
  | 'Kafka'
  | 'JUnit'
  | 'Mockito'
  | 'ARCore'
  | 'JavaFX'
  | 'shadcn/ui'
  | 'MySQL'
  | 'MariaDB'
  | 'MongoDB'
  | 'ElasticSearch'
  | 'Redis'
  | 'PostgreSQL'
  | 'SQLite'
  | 'Cassandra'
  | 'CouchDB'
  | 'Neo4j'
  | 'DynamoDB'
  | 'Firebase'
  | 'CockroachDB'
  | 'Oracle'
  | 'Google Cloud Platform'
  | 'DigitalOcean'
  | 'Railway'
  | 'Heroku'
  | 'Netlify'
  | 'Openshift'
  | 'Vercel'
  | 'AWS'
  | 'Azure'
  | 'Docker'
  | 'Kubernetes'
  | 'GitHub Pages'
  | 'GitLab Pages'
  | 'Bitbucket Pages'
  | 'Surge'
  | 'Render'
  | 'Fly'
  | 'Cloudflare Workers'
  | 'Cloudflare KV'
  | 'Cloudflare Durable Objects'
  | 'Cloudflare Stream'
  | 'Cloudflare Workers KV'
  | 'Cloudflare Pages'
  | 'Azure DevOps'

export type Work = {
  startDate: string
  endDate: string
  company: string
  title: string
  description: string
  technologies: Technologies[]
}

export type IPortfolioConfig = {
  work: Work[]
}
